# -*- coding: utf-8 -*-
"""KMeans Cluster analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jz40vt7FkRGke74O3GA_DDhwxQTkkjil
"""

# =========================================
# CLUSTER ANALYSIS USING K-MEANS
# ON SAMPLE DATASET (IRIS DATASET)
# =========================================

# Import required libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_iris
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score

iris = load_iris()
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)

print(df.head())

# -----------------------------------------
# Step 1: Load Sample Dataset (Iris)
# -----------------------------------------
iris = load_iris()
X = iris.data
feature_names = iris.feature_names

df = pd. DataFrame(X,columns=feature_names)
print(pd.DataFrame(df))

# ------------------------------------------
# Step 2: Standardize the Data
# ------------------------------------------
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# --------------------------------------
# Step 3: Elbow Method
# --------------------------------------
wcss = []

for i in range(1,11):
  kmeans = KMeans(n_clusters=i, random_state=42, n_init=10)
  kmeans.fit(X_scaled) # Fixed: lowercase 's'
  wcss.append(kmeans.inertia_)

plt.figure(figsize=(8,5))
plt.plot(range(1,11), wcss, marker='o')
plt.title("Elbow Method")
plt.xlabel("Number of Clusters")
plt.ylabel("WCSS")
plt.grid(True)
plt.show() # Fixed: plt instead of plot

# ------------------------------------------
# Step 4: Apply K-Means (K=3 for Iris)
# ------------------------------------------
kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
clusters = kmeans.fit_predict(X_scaled)

# Add cluster labels to dataframe
df['Cluster'] = clusters

# ------------------------------------------
# Step 5: Silhouette Score
# ------------------------------------------
score = silhouette_score(X_scaled, clusters)
print("\nSilhouette Score:", score)

# ------------------------------------------
# Step 6: Cluster Visualization (2 Features)
# ------------------------------------------
plt.figure(figsize=(8,6))
sns.scatterplot(x=X_scaled[:, 0], y=X_scaled[:, 1],
                hue=clusters, palette='viridis', s=70)

# Plot centroids
centroids = kmeans.cluster_centers_
plt.scatter(centroids[:, 0], centroids[:, 1],
            s=200, c='red', marker='X', label='Centroids')

plt.title("K-Means Clustering on Iris Dataset")
plt.xlabel(feature_names[0])
plt.ylabel(feature_names[1])
plt.legend()
plt.grid(True)
plt.show()

# ------------------------------------------
# Step 7: Print Cluster Centers
# ------------------------------------------
print("\nCluster Centers (Scaled Data):")
print(centroids)